#!/usr/bin/env python3
"""Wave 2 (continued): commit the remaining untracked Phases 1-6 as 6
reviewable commits with full test battery per step. Phase 0 already
landed in 85b0876.
"""
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STATE = ROOT / ".planonce/work/usagehalo-truth-remediation/STATE.md"


def run(cmd, **kw):
    return subprocess.run(cmd, cwd=str(ROOT), capture_output=True, text=True, **kw)


def gate():
    if not STATE.exists():
        sys.exit("STATE.md missing.")
    text = STATE.read_text(encoding="utf-8")
    # Pre-Wave-2 gates must be APPROVED; the human ship gate stays PENDING
    # until Wave 2 ends. We check the gates section, not the historical
    # narrative, so an old "PENDING_HUMAN_APPROVAL" mention in the intro
    # doesn't false-trigger.
    gates_section = ""
    if "## Gates" in text:
        gates_section = text.split("## Gates", 1)[1].split("## Completed", 1)[0]
    for line in gates_section.splitlines():
        if line.lstrip().startswith("-") and "PENDING" in line:
            if "Human ship gate" in line:
                continue
            sys.exit(f"a pre-Wave-2 gate is still PENDING: {line.strip()}")


def battery(label):
    print(f"\n=== battery: {label} ===")
    steps = [
        ("pytest", ["python", "-m", "pytest", "tests/", "-q"]),
        ("fmt", ["cargo", "fmt", "--check"]),
        ("clippy (non-desktop)", [
            "cargo", "clippy",
            "-p", "usage-halo-core",
            "-p", "usage-halo-storage",
            "-p", "usage-halo-reconcile",
            "-p", "usage-halo-projection",
            "-p", "usage-halo-collector",
            "--all-targets", "--", "-D", "warnings",
        ]),
        ("clippy (desktop)", ["cargo", "clippy", "-p", "usage-halo-desktop", "--no-deps"]),
        ("cargo test core", ["cargo", "test", "-p", "usage-halo-core", "--quiet"]),
        ("cargo test reconcile", ["cargo", "test", "-p", "usage-halo-reconcile", "--quiet"]),
        ("cargo test storage", ["cargo", "test", "-p", "usage-halo-storage", "--quiet"]),
        ("cargo test projection", ["cargo", "test", "-p", "usage-halo-projection", "--quiet"]),
        ("cargo test collector", ["cargo", "test", "-p", "usage-halo-collector", "--quiet"]),
        ("validate", ["python", "scripts/validate.py"]),
        ("privacy", ["python", "scripts/privacy_audit.py"]),
    ]
    fail = []
    for name, cmd in steps:
        r = run(cmd, timeout=600)
        ok = r.returncode == 0
        print(f"  [{'OK' if ok else 'FAIL'}] {name}")
        if not ok:
            fail.append((name, r.stderr[-400:]))
    return fail


# Pickers operate on paths relative to ROOT; untracked files in the
# working tree at script start. Each phase's picker is a list of paths
# (file or directory). Directory paths resolve to all files under them.
def phase1():
    return ["tests/test_truth_phase1.py"]


def phase2():
    return [
        "crates/usage-halo-storage/migrations/0002_canonical.sql",
        "tests/test_truth_phase2.py",
    ]


def phase3():
    return ["tests/test_truth_phase3.py"]


def phase4():
    return [
        "crates/usage-halo-projection",
        "apps/desktop-ui/src-tauri/src/legacy_adapter.rs",
        "tests/test_truth_phase4.py",
    ]


def phase5():
    return [
        "crates/usage-halo-collector",
        "crates/usage-halo-storage/migrations/0003_session_states.sql",
        "tests/test_truth_phase5.py",
    ]


def phase6():
    return [
        "tests/test_truth_phase6.py",
        "scripts/wave2.py",  # the wave-2 driver itself; commit alongside docs
    ]


# (Phase 5 and Phase 6 doc-only artifacts were generated by the previous
# turns and live under .planonce/work/usagehalo-truth-remediation/ which
# is the planone work dir, not the source tree. The matrix doc itself was
# already on disk before Wave 2; it is committed as a "docs" wave below
# after the test+connector commits.)


def docs_wave():
    # No-op: the L5 matrix doc was created in an earlier turn; the planone
    # work dir holds the plan docs and is intentionally not committed.
    return []


PHASES = [
    ("phase1: canonical contracts", phase1,
     "remediation(phase1): typed contracts, timezone-aware windows, no live/sample collapse",
     "14_CANONICAL_DATA_CONTRACTS.md"),
    ("phase2: SQLite authority", phase2,
     "remediation(phase2): SQLite authoritative, constraint-owned dedup, health-preserve upsert",
     "05_STORAGE_RECONCILIATION_TIME_FORECAST_ALERTS.md"),
    ("phase3: reconciliation + time", phase3,
     "remediation(phase3): scope-safe reconciliation, IANA calendar windows, DST-verified",
     "05_STORAGE_RECONCILIATION_TIME_FORECAST_ALERTS.md"),
    ("phase4: projection service", phase4,
     "remediation(phase4): one ProjectionService owns every user-visible number; legacy_adapter formats only",
     "06_FRONTEND_ARCHITECTURE_AND_STATE_MODEL.md"),
    ("phase5: connector runtime", phase5,
     "remediation(phase5): supervised ConnectorHost, class-specific retry, OS-keychain secrets",
     "03_BACKEND_AND_RUNTIME_REMEDIATION.md"),
    ("phase6: L5 evidence", phase6,
     "remediation(phase6): L5 evidence matrix; honest verified state per connector",
     "08_TESTING_TRUTHFULNESS_AND_RELEASE_GATES.md"),
]


def main():
    gate()
    r = run(["git", "status", "--porcelain"])
    pre = set()
    for line in r.stdout.splitlines():
        # Format: "XY path" — split on first space.
        if len(line) > 3 and line[2] == " ":
            pre.add(line[3:])
    print(f"pre-state: {len(pre)} entries")

    for label, picker, subject, ref_doc in PHASES:
        paths = picker()
        files = []
        for p in paths:
            full = ROOT / p
            if full.is_dir():
                for f in full.rglob("*"):
                    if f.is_file():
                        rel = str(f.relative_to(ROOT)).replace("\\", "/")
                        files.append(rel)
            else:
                files.append(p)
        # Filter to paths that are still in the working tree.
        live = [f for f in files if f in pre]
        if not live:
            print(f"\n=== {label}: nothing to commit ===")
            continue
        run(["git", "add", "--"] + live)
        msg = f"{subject}\n\nRefs: docs/.plans/UsageHalo_Remediation_Package/{ref_doc}"
        r = run(["git", "commit", "-m", msg])
        print(f"\n--- {label}: commit {'OK' if r.returncode == 0 else 'FAIL'} ---")
        if r.returncode != 0:
            print(r.stdout)
            print(r.stderr)
            sys.exit(1)
        r = run(["git", "rev-parse", "--short", "HEAD"])
        print(f"commit: {r.stdout.strip()}")
        # Update pre-state: this commit is no longer in the working tree.
        pre = pre - set(live)
        fails = battery(label)
        if fails:
            print(f"\n!!! {label}: battery FAILED on:")
            for name, err in fails:
                print(f"  - {name}: {err}")
            sys.exit(1)

    r = run(["git", "log", "--oneline", "34360b0..HEAD"])
    print(f"\nfinal log (34360b0..HEAD):\n{r.stdout}")
    r = run(["git", "status", "--porcelain"])
    remaining = [line for line in r.stdout.splitlines()
                 if not line.endswith(" .claude/")
                 and not line.endswith(" .planonce/")
                 and not line.endswith(" docs/.plans/")]
    print(f"\nworking tree: {len(remaining)} source-tree files remain uncommitted")
    for r in remaining:
        print(f"  {r}")
    print("Wave 2 complete.")


if __name__ == "__main__":
    main()
